### ISSUE TITLE
Nested routes are not working

### ISSUE THREAD

**Issue by hamzalakrati** [MohammedSaberMohammed/protected-react-routes-generator#1]
Nested routes are not working, if we try to put another <Switch> with <Route> in a component , We won't be able to access it.

**Comment by MohammedSaberMohammed** [comment]
could you please provide a full description of ur scenario and an example of what you want and I will implement it if it's possible?

**Comment by MohammedSaberMohammed** [comment]
@hamzalakrati could u please provide the details mentioned above ?

**Comment by MohammedSaberMohammed** [comment]
I'll close the issue because there is no enough informations.
